=== powerd6/specification/docs/schemas/module.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://specification.powerd6.org/schemas/module.json",
  "title": "module",
  "type": "object",
  "description": "A document that contains information detailing and explaining rules and/or content, meant to be used for rendering by powerd6.",
  "properties": {
    "title": {
      "description": "The title of the module",
      "type": "string"
    },
    "description": {
      "description": "The human-readable description of what the module contains.",
      "type": "string"
    },
    "source": {
      "description": "A hyperlink to the where the module is hosted.",
      "type": "string",
      "format": "uri"
    },
    "types": {
      "description": "A collection of types that are defined in this module",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-_]+$": {
          "$ref": "https://specification.powerd6.org/schemas/type.json"
        }
      }
    },
    "content": {
      "description": "A collection of contents defined in this module, the keys of the map are the unique identifiers of the content pieces",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-_]+$": {
          "type": "object",
          "properties": {
            "id": {
              "description": "The unique identifier of the content piece.",
              "type": "string",
              "pattern": "^[a-zA-Z0-9-_]+$"
            },
            "type": {
              "description": "The unique identifier of the content type.",
              "type": "string",
              "pattern": "^[a-zA-Z0-9-_]+$"
            }
          },
          "additionalProperties": true,
          "required": [
            "type"
          ]
        }
      }
    }
  },
  "required": [
    "title",
    "description",
    "source"
  ],
  "additionalProperties": false
}

=== powerd6/specification/docs/schemas/module.example.json
{
    "title": "generic-spells",
    "description": "A collection of simple spells for the powerd6 system.",
    "source": "https://github.com/sample-user/generic-spells",
    "types": {
        "spell": {
            "description": "Arcane or mystical arts that can be used inside or outside combat.",
            "schema": {
                "properties": {
                    "name": {
                        "description": "The name of the spell.",
                        "type": "string"
                    },
                    "recovery": {
                        "description": "How many turns must be passed before using the spell again.",
                        "type": "number"
                    },
                    "effect": {
                        "description": "The effect that is executed when the spell is used.",
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "recovery",
                    "effect"
                ]
            },
            "rendering": {
                "txt": "${name}:\n(Recovery ${recovery})\n${effect}",
                "md": "# ${name}\n> Recovery ${recovery}\n\n${effect}"
            }
        }
    },
    "content": {
        "fireball": {
            "type": "spell",
            "name": "Fireball",
            "recovery": 2,
            "effect": "Create an orb of flames that can be thrown with magical energy."
        }
    }
}
